### PR TITLE
Mac host note

### PR DESCRIPTION
**Pull request by kraigu**
Note that Macs are not known to work as Docker hosts. I think but can't prove that Windows will likely have similar issues.

### CODE REVIEW

**Comment by clcollins** [comment]
I *think* this is a consequence of the Docker daemon running in a virtual machine on the Mac host (assuming that's how you're doing it; it's a common setup).  

I will track down a spare Mac system and see if I can reproduce.

**Comment by clcollins** [comment]
@amerck: can you try running a honeypot on your laptop and reporting to our central instance?

**Comment by kraigu** [comment]
I accidentally this instead of a new pull request for the cowrie docs. :( Sorry, github newbie.

BTW, the original pull request was actually an update to the documentation to reflect that Macs work differently, not a request for help. I didn't notice the tag had been added until just now. :)

You can just merge both in if you like, or kill the pull request and I'll send two more? Whatever is easiest.

**Comment by JesseBowling** [comment]
Going to kill this one in favor of any future requests. :)

**Pull request closed without merging**
